apps/doctors/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'doctors'
urlpatterns = [
    path('visit_profile/', views.booking, name='booking'),
    path('partner/', views.partner, name='partner_with'),
    path('blog/', views.blog, name='blog_view'),
    path('add_blog/', views.blog_add, name='add_blog'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('schedule/', views.schedule_meet, name='schedule_meet'),
    path('all_doc/', views.doctor, name='doctor'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'
urlpatterns = [
    
    path('patient_profile/', views.patient_profile, name='profile'),
    path("video_call/", views.video_call, name='video call'),
    path("meeting/", views.meeting, name='meeting'),
    path('patient_login/', views.patient_login, name='patient_login'),
    path('patient_edit/', views.patient_edit, name='patient_edit'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new_index, name='dashboard'),
]

meetMyDoc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('patients/', include('apps.patients.urls')),
    path('doctor/', include('apps.doctors.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/patients/models.py
from django.db import models

# Create your models here.

apps/patients/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# Create your views here.





def patient_profile(request):
	return render(request, 'patients/patient_profile.html')

def patient_login(request):
	return render(request, 'patients/patient_login.html')

def video_call(request):
    return render(request, 'video/video_call.html')
    #return HttpResponse("This is Video call page")

def meeting(request):
    return render(request, 'video/meeting.html')

def patient_edit(request):
	return render(request, 'patients/patient_edit.html')

templates/patients/patient_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %} meetMyDoctor | Profile {% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css" />
<style>

.row.content {height: 600px}

/* Style the side navigation */
.sidenav {
  height: 100%;
  width: 300px;
  background-color: cadetblue;
  overflow-x: hidden;
}


/* Side navigation links */
.sidenav a {
  color: black;
  padding: 20px;
  text-decoration: none;
  display: block;
  font-size: 22px;
}

/* Change color on hover */
.sidenav a:hover {
  background-color: white;
  color: black;
}

@media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
</style>
{% endblock %}
{% block content %}

    <header style="padding: 3px; background-color: #005EB1; color: white; width: 100%;">
    <nav >
        <div class="nav-wrapper navbar-style">
            <a href="{% url 'home:index' %}"><img class="brand-logo" src="{% static 'icon/meetmyDoctor.png' %}"></a>
            <ul id="nav-mobile" class="righthide-on-med-and-down" style="display: inline-flex;">
           
                <li><a href="{% url 'home:index' %}" class="button" id="rcorners">Logout</a></li>
            </ul>
        </div>
    </nav>
</header> 
<div class="container-fluid">
 <div class="row content">
    <div class="col-sm-3 sidenav">
      <a href="#">View Appointment</a>
      <a href="{% url 'patients:patient_edit' %}">Edit Profile</a>
      <a href="{% url 'patients:profile' %}">Change Password</a>
      <a href="#">My Payment</a>
      <a href="{% url 'patients:video call' %}">Join meeting</a>
      <a href="#">My Prescription</a>
    </div>

   <div class="col-sm-9 my-4">
     <h4>Edit Profile</h4>
     <div class="content">
    
    <form class="row " style="padding:0px 120px 30px 120px;" method ="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-6">
            <label for="inputname" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name" required  title="Enter alphabets only">
        </div>
        <div class="col-md-6">
            <label for="inputname" class="form-label">Age</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter your age" required >
        </div>
        <div class="col-md-6">
            <label for="inputaddress" class="form-label">Address</label>
            <input type="text" class="form-control" id="address", name="address" placeholder="Enter your address" required>
        </div>
        <div class="col-md-6">
            <label for="inputphoneno" class="form-label">Phone No</label>
            <input type="phone" class="form-control" id="phone_no", name="phone_no" placeholder="Enter your phone no" required pattern="/[0-9]*{10}/" title="Enter in the format xxxxxxxxx ">
        </div>
        <div class="col-md-6">
            <label for="inputemail" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email"  pattern="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?" title="Enter valid email address" required/>
        </div>
        
        <div class="col-md-6">
            <label for="thumbnail">Profile Photo <span class="text-muted">(Optional)</span></label>
                    <input name="thumbnail" type="file" id="thumbnail" class="form-control-file" onchange="imageValidation()">
        </div>
        <div class="col-12 text-center my-4">
            <button type="submit" class="btn btn-outline-success" style="border: 2px solid black; border-radius:15px;width:200px;">Submit</button>
        </div>
    </form>
</div>

   </div>
 </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
(function() {
    'use strict'
    window.addEventListener('load', function() {
        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.getElementsByClassName('needs-validation')

        // Loop over them and prevent submission
        Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault()
                    event.stopPropagation()
                }
                form.classList.add('was-validated')
            }, false)
        })
    }, false)
}())
</script>
<!-- Script for Image Validation -->
<script type="text/javascript">
function imageValidation() {
    var fileInput = document.getElementById('thumbnail');
    var filePath = fileInput.value;
    var allowedExtensions = /(\.jpg|\.jpeg|\.png|\.gif)$/i;
    if (!allowedExtensions.exec(filePath)) {
        alert('Please upload file having extensions .jpeg, .jpg, .png or .gif only.');
        fileInput.value = '';
    }
}

</script>
{% endblock %}

templates/patients/patient_login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} meetMyDoctor | Patient Login {% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css" />
<style >
	.header{
  height: 100vh;
}

.nav-wrapper{
  background-color: #005EB1;

}

.righthide-on-med-and-down{
  float: right;
  
}

#nav-mobile{
  
}

.navbar-style{
  box-shadow: 0 5px 10px #efefef;
}

.brand-logo{
  height: 60px;
  padding: 2px 10px;
  margin-left: 56px;

}

.button {
  background-color: #FFF;
  border: none;
  color: black;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 13px;
  margin: 4px 2px;
  cursor: pointer;
  position: absolute;
  right: 150px;
  top: 8px;
  border-radius: 30px;
  padding: 10px;
  width: 100px;
  height: 40px;
}

#blogs{
  position: absolute;
  right: 300px;
  top: 15px;
  font-family: -apple-system,BlinkMacSystemFont,"Segoe UI","Helvetica Neue",sans-serif;
  font-size: 20px;
  color: #fff;
}

</style>
{% endblock %}
{% block content %}
<header style="padding: 3px; background-color: #005EB1; color: white; width: 100%;">
    <nav >
        <div class="nav-wrapper navbar-style">
            <a href="{% url 'home:index' %}"><img class="brand-logo" src="{% static 'icon/meetmyDoctor.png' %}"></a>
            <ul id="nav-mobile" class="righthide-on-med-and-down" style="display: inline-flex;">
                <li><a href="{% url 'patients:profile' %}" class="button" id="rcorners">View Profile</a></li>
            </ul>
        </div>
    </nav>
</header> 

    <div class="cover">
        <div>
        <h1>Finding a doctor was <br>never so easy!</h1><br>
        <p> Search for the best practitioners near you<br> just in one click</p>
        <form method="post" action="{% url 'doctors:doctor' %}">
            {% csrf_token %}
        <div class="wrap">
            <div class="search">
               <input type="text" class="searchTerm" name="search" placeholder="What are you looking for?">
               <button type="submit" class="searchButton" style="width: 50%;">
                 Search
              </button>
            </div>
         </div>
         </form>
        </div>
        <img src="{% static 'icon/caver img.jpg' %}" alt="cover img" id="coverimg" width="800" height="500">
    </div>

    
    <h2 class="heads" style="margin-top: 60px;">We Bring to you cure that works for you</h2>
   <hr style="width:10%; height: 5px; color: #00BF42; background-color:#00BF42">
  
   <div style="margin: 20px;"  class="row2">
    <div class="column2">
      <img src="{% static 'icon/Mask Group 1.png' %}" alt="Ayurveda" style="width:100%">
      <div class="titles1"><p>Ayurveda</p></div>
    </div>
    <div class="column2">
      <img src="{% static 'icon/Mask Group 2.png' %}" alt="Homeopathy" style="width:100%">
      <div class="titles1"><p>Homeopathy</p></div>
    </div>
    <div class="column2">
      <img src="{% static 'icon/Mask Group 3.png' %}" alt="Allopathy" style="width:100%">
      <div class="titles1"><p>Allopathy</p></div>
    </div>
  </div>  

    <div class="boxed">
        <div style="margin-left: 90px;">
       <h1 style=" color:#FF444F; font-size: 40px; margin: 30px;">Are you a Doctor?</h1>
       <h3 style="margin-bottom: 50px;">What we have to offer you</h3>
       
         <a href="{% url 'doctors:partner_with' %}" class="button2" style="text-decoration: none; color: white;">Partner with Us</a></div>
         <div style="width:  500px;">
         <p style="margin: 40px; font-size: 15px; font-style: ">1. List your practices online <br><br>2. Work Remotely<br><br> 3. Schedule appointments, make your day organised<br><br>4. Virtually connect with clients <br><br> 5. Keep sharing blogs</p></div>
         <div >
            <img src="{% static 'icon/Mask Group 4.png' %}" alt="img" height="250px" width="300px">
         </div>
        </div>


{% endblock %}
{% block scripts %}
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
AOS.init({
    offset: 150,
});
</script>
{% endblock %}	

templates/patients/patient_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} meetMyDotor | Profile {% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css" />
<style>

.row.content {height: 600px}

/* Style the side navigation */
.sidenav {
  height: 100%;
  width: 300px;
  background-color: cadetblue;
  overflow-x: hidden;
}


/* Side navigation links */
.sidenav a {
  color: black;
  padding: 20px;
  text-decoration: none;
  display: block;
  font-size: 22px;
}

/* Change color on hover */
.sidenav a:hover {
  background-color: white;
  color: black;
}

@media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
</style>
{% endblock %}
{% block content %}

    <header style="padding: 3px; background-color: #005EB1; color: white; width: 100%;">
    <nav >
        <div class="nav-wrapper navbar-style">
            <a href="{% url 'home:index' %}"><img class="brand-logo" src="{% static 'icon/meetmyDoctor.png' %}"></a>
            <ul id="nav-mobile" class="righthide-on-med-and-down" style="display: inline-flex;">
                <li><a href="{% url 'home:index' %}" class="button" id="rcorners">Logout</a></li>
            </ul>
        </div>
    </nav>
</header>
<div class="container-fluid">
 <div class="row content">
    <div class="col-sm-3 sidenav">
      <a href="#">View Appointment</a>
      <a href="{% url 'patients:patient_edit' %}">Edit Profile</a>
      <a href="{% url 'patients:profile' %}">Change Password</a>
      <a href="#">My Payment</a>
      <a href="{% url 'patients:video call' %}">Join meeting</a>
      <a href="#">My Prescription</a>
    </div>
      <div class="col-sm-9 my-4">
     <h2>Change Password</h2>
     <form class="row g-3 my-4" style="padding:0px 120px 30px 120px;" method ="post" action ="/partner with us">
        {% csrf_token %}
        <div class="col-md-8">
            <label for="inputtitle" class="form-label">New Password</label>
            <input type="text" class="form-control" id="Npass" name="Npass" placeholder="Enter new password" required pattern="/^[a-zA-Z]+ [a-zA-Z]+$/" title="Enter alphabets only">
        </div>
        <div class="col-md-8">
            <label for="desc" class="form-label">Confirm Password</label>
            <input type="text" class="form-control" id="Rpass" name="Rpass" placeholder="Retype password" required>
        </div>
        <div class="col-12 my-4">
            <button type="submit" class="btn btn-outline-success" style="border: 2px solid black; border-radius:15px;width:100px;">Submit</button>
        </div>
     </form>
   </div>
 </div>
</div>
{% endblock %}
{% block scripts %}
<script >
    
function matchpass(){
var firstpassword=document.f1.password.value;
var secondpassword=document.f1.password2.value;

if(firstpassword==secondpassword){
return true;
}
else{
alert("password must be same!");
return false;
}
}

</script>

{% endblock %}