accounts/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('' ,  views.home , name="home"),
    path('login/', views.login_page, name='login_page'),
    path('signup/success/', views.signup_success, name='signup_success'),
    path('authenticated/', views.account_authenticated, name='account_authenticated'),
    

]

apps/doctors/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'doctors'
urlpatterns = [
    path('visit_profile/', views.booking, name='booking'),
    path('partner/', views.partner, name='partner_with'),
    path('blog/', views.blog, name='blog_view'),
    path('add_blog/', views.blog_add, name='add_blog'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('schedule/', views.schedule_meet, name='schedule_meet'),
    path('all_doc/', views.doctor, name='doctor'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new_index, name='dashboard'),
]

meetMyDoc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('patients/', include('apps.patients.urls')),
    path('doctor/', include('apps.doctors.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/doctors/models.py
from django.db import models
from django.conf import settings
# Create your models here.

def login_thumbmail_path(instance, filename):
    return f'doctor/{instance.id}/thumbnail/{filename}'

def edit_thumbmail_path(instance, filename):
    return f'profile/{instance.id}/thumbnail/{filename}'

class Login(models.Model):
    name = models.CharField(max_length=100)
    spec = models.CharField(max_length=20) 
    address = models.CharField(max_length=50)
    experience = models.CharField(max_length=3000)
    phone_no = models.CharField(max_length=13) 
    email = models.EmailField(max_length=50) 
    desc = models.CharField(max_length=2500)
    thumbnail = models.FileField(upload_to=login_thumbmail_path, null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def get_thumbnail_url(self):
        if self.thumbnail and hasattr(self.thumbnail, 'url'):
            return self.thumbnail.url
        else:
            return settings.STATIC_URL + 'accounts/icon/google.png'

class Profile(models.Model):
    name = models.CharField(max_length=100)
    hos_name = models.CharField(max_length=100)
    spec = models.CharField(max_length=20) 
    address = models.CharField(max_length=50)
    experience = models.CharField(max_length=3000)
    phone_no = models.CharField(max_length=13) 
    email = models.EmailField(max_length=50) 
    fee = models.CharField(max_length=50)
    time = models.CharField(max_length=250)
    thumbnail = models.FileField(upload_to=edit_thumbmail_path, null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def get_thumbnail_url(self):
        if self.thumbnail and hasattr(self.thumbnail, 'url'):
            return self.thumbnail.url
        else:
            return settings.STATIC_URL + 'accounts/icon/google.png'
# Create your models here.

apps/doctors/forms.py
from django import forms

from .models import Login


class LoginCreation(forms.ModelForm):
    class Meta:
        model = Login
        fields = ['name', 'address','spec', 'experience','phone_no','email','desc','thumbnail']

    def clean(self):
        cleaned_data = self.cleaned_data
        return cleaned_data

apps/doctors/views.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Login, Profile
from django.db.models import Q
# Create your views here.

def booking(request):
	data1=Profile.objects.filter(name='Manisha Verma')
	return render(request, 'doctor/view_profile.html',{'data1':data1})

@permission_required('doctor.partner_with', raise_exception=True)
def partner(request):
	if request.method == 'POST':
		name = request.POST['name']
		spec = request.POST['spec']
		address = request.POST['address']
		experience = request.POST['experience']
		phone_no = request.POST['phone_no']
		email= request.POST['email']
		desc= request.POST['desc']
		thumbnail= request.FILES.get('thumbnail')
		login = Login(
            name=name, spec=spec, address=address, experience=experience, phone_no=phone_no, email=email, desc=desc,thumbnail=thumbnail, )
		login.save()
		messages.success(request, "Doctor added successfully!")
		return redirect('doctors:add_blog')

	return render(request, 'doctor/partner_with_us.html')

def blog(request):
	return render(request, 'blog/blog.html')

def blog_add(request):
	return render(request, 'blog/blog_register.html')

def edit_profile(request):
	if request.method == 'POST':
		name = request.POST['name']
		hos_name = request.POST['hos_name']
		spec = request.POST['spec']
		address = request.POST['address']
		experience = request.POST['experience']
		phone_no = request.POST['phone_no']
		email= request.POST['email']
		fee= request.POST['fee']
		time= request.POST['time']
		thumbnail= request.FILES.get('thumbnail')
		edit = Profile(
            name=name, hos_name= hos_name, spec=spec, address=address, experience=experience, phone_no=phone_no, email=email, fee=fee, time=time, thumbnail=thumbnail)
		edit.save()
		messages.success(request, "Doctor added successfully!")
		return redirect('doctors:add_blog')
	return render(request, 'doctor/profile/edit_profile.html')

def doctor(request):
	search_post = request.GET.get('search')
	
	if search_post:
		data = Profile.objects.filter(Q(spec__icontains=search_post))

	else:
		data = Profile.objects.all()

	return render(request, 'doctor/doctor_list.html',{'data':data})

def schedule_meet(request):
	return render(request, 'doctor/profile/schedule.html')

templates/doctor/doctor_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} meetMyDoctor | DoctorView {% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'patients/style.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css" />
<style>
.col-md-4 {
    display: inline-block;
    margin-left: -4px;
}

.col-md-4 img {
    width: 100px;
    height: 172px;
    padding: 10px;
}
</style>
{% endblock %}
{% block content %}
<header style="padding: 3px; background-color: #005EB1; color: white; width: 100%;">
    <nav >
        <div class="nav-wrapper navbar-style">
            <a href="{% url 'home:index' %}"><img class="brand-logo" src="{% static 'icon/meetmyDoctor.png' %}"></a>
            <ul id="nav-mobile" class="righthide-on-med-and-down" style="display: inline-flex;">
                <li><a href="{% url 'accounts:login_page' %}" class="button" id="rcorners">Login/SignUp</a></li>
            </ul>
        </div>
    </nav>
</header> 
<div class="container  my-4">
    <div class="row">
        {% for edit_profile in data %}
        <div class="col-6 my-3">
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-4" style=" text-align: left; padding-left: 1rem;">
                        <img src="/media/{{edit_profile.thumbnail}}" style="width: 150px; height:150px; padding-left:0;">
                        <span>{{edit_profile.name}}</span><br>
                        <span><small class="text-muted">{{edit_profile.spec}}</small></span>
                    </div>
                    <div class="col-md-8" style=" text-align: left;">
                        <div class="card-body">
                            <h5 class="card-title">{{edit_profile.hos_name}}</h5>
                            <p class="card-text">Experience: {{edit_profile.experience}}<br>Fees:{{edit_profile.fee}}<br>Address: {{edit_profile.address}}<br>Time:{{edit_profile.time}}</p>
                            <a href="{% url 'doctors:booking'%}" class="btn btn-primary">Book Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
</div>
{% endblock %}

templates/doctor/partner_with_us.html
{% extends 'base.html' %}

{% load static %}

{% block title %} meetMyDoctor | Doctor Login {% endblock %}


{% block style %}
<link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css" />
  <style >
      .checked {
    color: orange;
  }
  
  .textual {
    position: absolute;
    top:200px;
    left: 50px;
    font-family:Script MT;
    font-size:40px;
    text-align:center;
  }
  
  .content {
    border:2px groove aqua;
    height:630px;
    max-width:1200px;
    margin: 30px 0px 0px 30px;
  }
  
  .content1 {
    background: darkturquoise;
    padding: 10px;
    height: 70px;
    max-width:1200px;
  }
  
  .content2 {
    background: orange;
    padding: 10px;
    height: 70px;
    max-width:95%;
    margin: 30px 0px 0px 30px;
  }
  
  html,body { 
      height: 100%; 
  }
  
  .global-container{
      height:100%;
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: #f5f5f5;
  }
  
  form{
      padding-top: 10px;
      font-size: 14px;
      margin-top: 30px;
  }
  
  .card-title{ font-weight:300; }
  
  .btn{
      font-size: 14px;
      margin-top:20px;
  }
  
  .login-form{ 
      width:330px;
      margin:20px;
  }
  
  .sign-up{
      text-align:center;
      padding:20px 0 0;
  }
  
  .alert{
      margin-bottom:-30px;
      font-size: 13px;
      margin-top:20px;
  }

  * {
    box-sizing: border-box;
  }
  
  .container-fluid{
      padding: 3% 15% 7%;
  }
  
  .main-button{
      font-size: 2rem;
      padding: 2% 4% 2% 4%;
      margin: 5% 3% 5% 0;
      width: 150px;
      height: 50px;
  }
  
  /* Center website */
  .main {
    max-width: 1000px;
    margin: auto;
  }
  
  h1 {
    font-size: 50px;
    word-break: break-all;
  }
  
  .row {
    margin: 10px -16px;
  }
  
  /* Add padding BETWEEN each column */
  .row,
  .row > .leftcolumn {
    padding: 20px;
  }
  
  /* The "show" class is added to the filtered elements */
  .show {
    display: block;
  }
  
  
  
  /* Header/Blog Title */
  .header {
    padding: 5px;
    font-size: 10px;
    text-align: center;
    background: pink;
  }
  
  
  
  
  /* Create two unequal columns that floats next to each other */
  /* Left column */
  .leftcolumn {   
    float: left;
    width: 33.3%;  
  }
  
  /* Right column */
  .rightcolumn {
    float: left;
    width: 25%;
    padding-left: 20px;
  }
  
  /* Fake image */
  .fakeimg {
    background-color: white;
    width: 100%;
    padding: 20px;
  }
  
  /* Add a card effect for articles */
  .card {
     background-color: white;
     padding: 20px;
     margin-top: 20px;
  }
  
  /* Clear floats after the columns */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }
  
  /* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
  @media screen and (max-width: 800px) {
    .leftcolumn, .rightcolumn {   
      width: 100%;
      padding: 0;
    }
  }
  
  @media (min-width: 768px){
    .col-md-8 {
      flex: 0 0 auto;
      width: 66.6666666667%;
      direction: rtl;
          
  }
}

  @media (min-width: 1200px){
    .content {
      max-width: 95%;
  }
     .content1 {
         max-width: 100%;
     }

     .container {
         max-width: 100%;
     }

    
}

  </style>
{% endblock %}


{% block content %}
    <header style="padding: 3px; background-color: #005EB1; color: white; width: 100%;">
    <nav >
        <div class="nav-wrapper navbar-style">
            <a href="{% url 'home:index' %}"><img class="brand-logo" src="{% static 'icon/meetmyDoctor.png' %}"></a>
            <ul id="nav-mobile" class="righthide-on-med-and-down" style="display: inline-flex;">
                <li><a href="{% url 'accounts:login_page' %}" class="button" id="rcorners">Login/SignUp</a></li>
            </ul>
        </div>
    </nav>
</header> 
<!--div for upper border-->
<div class="container-fluid" style="background-image:linear-gradient(to right,#6397EB,#2BF589);padding: 20px;height: 80px;">
           <p style="font-size:28px;font-family: cursive;color: aliceblue;margin-top: 4px;">
            Partner With Us</p>
</div>
<!--div for image and text-->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <p class="textual" style="color:#63D0EB; width:100%;">Desperate to serve<br>your Services to<br>the People.
            <p class="textual" style="color:#F28910; top:380px; width:100%;">Collaborate with Us</p>
        </div>
        <div class="col-md-8">
           <img src="{% static 'icon/doctor/partner.jpg' %}" style="width:100%;height:100%;padding-left:100px;">
        </div>
    </div>
</div>
<!--div for form and box-->
<div class="content">
    <div class="content1">
           <p style="font-size:28px;font-family: cursive;color: aliceblue;margin-top: 4px; max-width:1200px;">
           List your practices on meetMyDoctor.....</p>
    </div>
    <form class="row " style="padding:0px 120px 30px 120px;" method ="post"enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-6">
            <label for="inputname" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name" required pattern="/^[a-zA-Z]*+ [a-zA-Z]*+$/" title="Enter alphabets only">
        </div>
        <div class="col-md-6">
            <label for="inputSpecialization" class="form-label">Specialization</label>
            <input type="text" class="form-control" id="spec", name="spec" placeholder="Enter your specialization" required pattern="/[A-Z][a-z]*+[\,\]/" title="Enter alphabets only">
        </div>
        <div class="col-md-6">
            <label for="inputaddress" class="form-label">Address</label>
            <input type="text" class="form-control" id="address", name="address" placeholder="Enter your address" required>
        </div>
        <div class="col-md-6">
            <label for="inputexperience" class="form-label">Experience</label>
            <input type="text" class="form-control" id="experience" name="experience" placeholder="How much experience you have" required pattern="^([0-9 ][a-zA-Z ]*[a-zA-Z]*)" title="Enter alphanumeric values">
        </div>
        <div class="col-md-6">
            <label for="inputphoneno" class="form-label">Phone No</label>
            <input type="phone" class="form-control" id="phone_no", name="phone_no" placeholder="Enter your phone no" required pattern="/[0-9]*{10}/" title="Enter in the format xxxxxxxxx ">
        </div>
        <div class="col-md-6">
            <label for="inputemail" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email"  pattern="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?" title="Enter valid email address" required/>
        </div>
        <div class="col-12">
            <label for="desc" class="form-label">Message</label>
            <input type="text" class="form-control" id="desc" name="desc" placeholder="Message" required>
        </div>
        <div class="col-md-6">
            <label for="exampleFormControlFile1" class="form-label">Medical Degree Certificate</label>
            <input type="file" name="thumbnail" class="form-control-file" id="thumbnail" required/>
        </div>
        <div class="col-md-6">
            <label for="inputPassword4" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputPassword4" name="password" placeholder="Password" required pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Password should contain atleast 1 digit, 1 uppercase, 1 lowercase, minimum length 8">
        </div>
        <div class="col-12 text-center my-4">
            <button type="submit" class="btn btn-outline-success" style="border: 2px solid black; border-radius:15px;width:200px;">Submit</button>
        </div>
    </form>
</div>


{% endblock %}