accounts/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('' ,  views.home , name="home"),
    path('login/', views.login_page, name='login_page'),
    path('signup/success/', views.signup_success, name='signup_success'),
    path('authenticated/', views.account_authenticated, name='account_authenticated'),
    

]

apps/doctors/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'doctors'
urlpatterns = [
    path('visit_profile/', views.booking, name='booking'),
    path('partner/', views.partner, name='partner_with'),
    path('blog/', views.blog, name='blog_view'),
    path('add_blog/', views.blog_add, name='add_blog'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('schedule/', views.schedule_meet, name='schedule_meet'),
    path('all_doc/', views.doctor, name='doctor'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new_index, name='dashboard'),
]

meetMyDoc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('patients/', include('apps.patients.urls')),
    path('doctor/', include('apps.doctors.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/blog/blog.html
 {% extends 'base.html' %}

{% load static %}

{% block title %} meetMyDoctor | Blog View {% endblock %}


{% block style %}
<link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css" />
<style >
 
  
  .container-fluid{
      padding: 3% 15% 7%;
  }
  
  .main-button{
      font-size: 2rem;
      padding: 2% 4% 2% 4%;
      margin: 5% 3% 5% 0;
      width: 150px;
      height: 50px;
  }
  
  /* Center website */
  .main {
    max-width: 1000px;
    margin: auto;
  }
  
  h1 {
    font-size: 50px;
    word-break: break-all;
  }
  
  .row {
    margin: 10px -16px;
  }
  
  /* Add padding BETWEEN each column */
  .row,
  .row > .leftcolumn {
    padding: 20px;
  }
  
  /* The "show" class is added to the filtered elements */
  .show {
    display: block;
  }
  
  
  
  
  /* Create two unequal columns that floats next to each other */
  /* Left column */
  .leftcolumn {   
    float: left;
    width: 33.3%;  
  }
  
  /* Right column */
  .rightcolumn {
    float: left;
    width: 25%;
    padding-left: 20px;
  }
  
  /* Fake image */
  .fakeimg {
    background-color: white;
    width: 100%;
    padding: 20px;
  }
  
  /* Add a card effect for articles */
  .card {
     background-color: white;
     padding: 20px;
     margin-top: 20px;
     height: 500px;
     width: 400px;
     text-align: left;
  }
  
  /* Clear floats after the columns */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }
  
  /* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
  @media screen and (max-width: 800px) {
    .leftcolumn, .rightcolumn {   
      width: 100%;
      padding: 0;
    }
  }
  
  @media (min-width: 768px){
    .col-md-8 {
      flex: 0 0 auto;
      width: 66.6666666667%;
      direction: rtl;
          
  }
}

  @media (min-width: 1200px){
    .content {
      max-width: 95%;
  }
     .content1 {
         max-width: 100%;
     }

     .container {
         max-width: 100%;
     }

    
}
</style>
{% endblock %}


{% block content %}
    <header style="padding: 3px; background-color: #005EB1; color: white; width: 100%;">
    <nav >
        <div class="nav-wrapper navbar-style">
            <a href="{% url 'home:index' %}"><img class="brand-logo" src="{% static 'icon/meetmyDoctor.png' %}"></a>
            <ul id="nav-mobile" class="righthide-on-med-and-down" style="display: inline-flex;">

                <li><a href="{% url 'doctors:blog_view' %}">
                        <p id="blogs">Blogs</p>
           
                <li><a href="{% url 'accounts:login_page' %}" class="button" id="rcorners">Login/SignUp</a></li>
            </ul>
        </div>
    </nav>
</header> 
  <div class="container-fluid" style="background-image:linear-gradient(to right,#6397EB,#2BF589);padding: 20px;height: 80px;">
           <center><p style="font-size:32px;font-family: cursive;color: aliceblue;margin-top: 4px;">
            Explore the world of Healthcare through the Blogs</p></center>
</div>
<div class="row">
   <div class="leftcolumn">
      <div class="card">
      <img src="{% static 'icon/Mask Group 1.png' %}" alt="Mountains" height="300" width="100%">
       <br> <h3>Aryuvedic</h3>
        <p style="font-size: 18px;">Aryuvedic medicines</p>
        <a href="1.html" hreflang="en">Read More</a>
      </div>
   </div>
    <div class="leftcolumn">
      <div class="card">
      <img src="{% static 'icon/Mask Group 2.png' %}" alt="Lights" height="300" width="100%">
        <br><h3>Allopathy</h3>
        <p style="font-size: 18px;">Allopathic medicine information</p>
        <a href="https://meesho.com/blog/different-types-cupboards-you-need-your-house" hreflang="en">Read More</a>
      </div>
    </div>
    <div class="leftcolumn">
      <div class="card">
      <img src="{% static 'icon/Mask Group 3.png' %}" alt="Nature" height="300" width="100%">
       <br><h3>Homoepathic</h3>
        <p style="font-size: 18px;">Homoepathic medicines information</p>
        <a href="https://meesho.com/blog/different-types-cupboards-you-need-your-house" hreflang="en">Read More</a>
      </div>
    </div>
       <div class="leftcolumn">
      <div class="card">
      <img src="{% static 'icon/Mask Group 1.png' %}" alt="Mountains" height="300" width="100%">
       <br> <h3>Aryuvedic</h3>
        <p style="font-size: 18px;">Aryuvedic medicines</p>
        <a href="1.html" hreflang="en">Read More</a>
      </div>
   </div>
    <div class="leftcolumn">
      <div class="card">
      <img src="{% static 'icon/Mask Group 2.png' %}" alt="Lights" height="300" width="100%">
        <br><h3>Allopathy</h3>
        <p style="font-size: 18px;">Allopathic medicine information</p>
        <a href="https://meesho.com/blog/different-types-cupboards-you-need-your-house" hreflang="en">Read More</a>
      </div>
    </div>
    <div class="leftcolumn">
      <div class="card">
      <img src="{% static 'icon/Mask Group 3.png' %}" alt="Nature" height="300" width="100%">
       <br><h3>Homoepathic</h3>
        <p style="font-size: 18px;">Homoepathic medicines information</p>
        <a href="https://meesho.com/blog/different-types-cupboards-you-need-your-house" hreflang="en">Read More</a>
      </div>
    </div>
       <div class="leftcolumn">
      <div class="card">
      <img src="{% static 'icon/Mask Group 1.png' %}" alt="Mountains" height="300" width="100%">
       <br> <h3>Aryuvedic</h3>
        <p style="font-size: 18px;">Aryuvedic medicines</p>
        <a href="1.html" hreflang="en">Read More</a>
      </div>
   </div>
    <div class="leftcolumn">
      <div class="card">
      <img src="{% static 'icon/Mask Group 2.png' %}" alt="Lights" height="300" width="100%">
        <br><h3>Allopathy</h3>
        <p style="font-size: 18px;">Allopathic medicine information</p>
        <a href="https://meesho.com/blog/different-types-cupboards-you-need-your-house" hreflang="en">Read More</a>
      </div>
    </div>
    <div class="leftcolumn">
      <div class="card">
      <img src="{% static 'icon/Mask Group 3.png' %}" alt="Nature" height="300" width="100%">
       <br><h3>Homoepathic</h3>
        <p style="font-size: 18px;">Homoepathic medicines information</p>
        <a href="https://meesho.com/blog/different-types-cupboards-you-need-your-house" hreflang="en">Read More</a>
      </div>
    </div>
{% endblock %}

templates/blog/blog_register.html
{% extends 'base.html' %}
{% load static %}
{% block title %} meetMyDotor | Blog {% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css" />
<style>

.row.content {height: 600px}

/* Style the side navigation */
.sidenav {
  height: 100%;
  width: 300px;
  background-color: cadetblue;
  overflow-x: hidden;
}


/* Side navigation links */
.sidenav a {
  color: black;
  padding: 20px;
  text-decoration: none;
  display: block;
  font-size: 22px;
}

/* Change color on hover */
.sidenav a:hover {
  background-color: white;
  color: black;
}

@media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
</style>
{% endblock %}
{% block content %}
 <header style="padding: 3px; background-color: #005EB1; color: white; width: 100%;">
    <nav >
        <div class="nav-wrapper navbar-style">
            <a href="{% url 'home:index' %}"><img class="brand-logo" src="{% static 'icon/meetmyDoctor.png' %}"></a>
            <ul id="nav-mobile" class="righthide-on-med-and-down" style="display: inline-flex;">

                <li><a href="{% url 'home:index' %}" class="button" id="rcorners">Logout</a></li>
            </ul>
        </div>
    </nav>
</header> 
<div class="container-fluid">
 <div class="row content">
    <div class="col-sm-3 sidenav">
      <a href="#">Schedule Appointment</a>
      <a href="{% url 'doctors:edit_profile' %}">Edit Profile</a>
      <a href="#">Change Password</a>
      <a href="#">View Appointment</a>
      <a href="#">Add Blogs</a>
      <a href="{% url 'doctors:schedule_meet' %}">Schedule meeting</a>
    </div>

   <div class="col-sm-9 my-4">
     <h2>Add Blogs</h2>
     <form class="row g-3 my-4" style="padding:0px 120px 30px 120px;" method ="post" action ="/partner with us">
        {% csrf_token %}
        <div class="col-md-6">
            <label for="inputtitle" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Enter title here" required pattern="/^[a-zA-Z]+ [a-zA-Z]+$/" title="Enter alphabets only">
        </div>
        <div class="col-md-8">
            <label for="desc" class="form-label">Description</label>
            <input type="text" class="form-control" id="desc" name="desc" placeholder="description" required>
        </div>
        <div class="col-md-6">
            <label for="exampleFormControlFile1" class="form-label">Upload Image</label>
            <input type="file" class="form-control" id="img" name="image" required>
        </div>
        
        <div class="col-12 my-4">
            <button type="submit" class="btn btn-outline-success" style="border: 2px solid black; border-radius:15px;width:100px;">Submit</button>
        </div>
     </form>
   </div>
 </div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
(function() {
    'use strict'
    window.addEventListener('load', function() {
        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.getElementsByClassName('needs-validation')

        // Loop over them and prevent submission
        Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault()
                    event.stopPropagation()
                }
                form.classList.add('was-validated')
            }, false)
        })
    }, false)
}())
</script>
<!-- Script for Image Validation -->
<script type="text/javascript">
function imageValidation() {
    var fileInput = document.getElementById('thumbnail');
    var filePath = fileInput.value;
    var allowedExtensions = /(\.jpg|\.jpeg|\.png|\.gif)$/i;
    if (!allowedExtensions.exec(filePath)) {
        alert('Please upload file having extensions .jpeg, .jpg, .png or .gif only.');
        fileInput.value = '';
    }
}
</script>
{% endblock %}